services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=platzi_playJ_db'
      - 'POSTGRES_PASSWORD=josmer.platzi'
      - 'POSTGRES_USER=josmer'
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/data/postgres'
volumes:
  pgdata: